name: compile, build, commit and release
on: [push]
jobs:
  Compile-LaTeX:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: derivata.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: derivata.pdf
          path: derivata.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ricorrenza.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: ricorrenza.pdf
          path: ricorrenza.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: logica.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: logica.pdf
          path: logica.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: formula_area.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: formula_area.pdf
          path: formula_area.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: curve.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: curve.pdf
          path: curve.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: forme_differenziali.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: forme_differenziali.pdf
          path: forme_differenziali.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: sistemi_lineari.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: sistemi_lineari.pdf
          path: sistemi_lineari.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tychonov.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: tychonov.pdf
          path: tychonov.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: inversione.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: inversione.pdf
          path: inversione.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: studioqualitativo.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: studioqualitativo.pdf
          path: studioqualitativo.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: senodienne.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: senodienne.pdf
          path: senodienne.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: uniformecontinuita.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: uniformecontinuita.pdf
          path: uniformecontinuita.pdf
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: teoremi.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: teoremi.pdf
          path: teoremi.pdf
  Create-Release:
    runs-on: ubuntu-latest
    needs: Compile-LaTeX
    if: startsWith(github.ref, 'refs/tags/') # make release on tag push
    steps:
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: derivata.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: ricorrenza.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: ricorrenza.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: ricorrenza.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: ricorrenza.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: logica.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: formula_area.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: curve.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: forme_differenziali.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: sistemi_lineari.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: formula_area.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: tychonov.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: inversione.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: studioqualitativo.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: senodienne.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: uniformecontinuita.pdf
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: teoremi.pdf
      - name: create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.pdf"
          artifactContentType: "application/pdf"
          body: "${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "this job's status is ${{ job.status }}."[17:45:49]emanuele@emanuele-XPS:~/AnalisiUno
